services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
      # - 81:80
      - 443:443
    networks:
      traefik:
        aliases:
          - proxy.traefik
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - ./logs:/var/log/traefik:rw
      - ./certs:/etc/traefik/certs:rw
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./providers:/etc/traefik/providers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"

      traefik.http.routers.traefik.entrypoints: "web,websecure"
      traefik.http.routers.traefik.rule: "Host(`traefik.jpabreu.com`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: "cloudflare"

      traefik.http.routers.wildcard.tls.domains[0].main: "jpabreu.com"
      traefik.http.routers.wildcard.tls.domains[0].sans : "*.jpabreu.com"
      traefik.http.routers.wildcard.tls.certResolver : "cloudflare"

networks:
  traefik:
    name: traefik
    ipam:
      config:
        - subnet: 192.168.3.0/24
