services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 4gb
    networks:
      - traefik
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      # - 8096:8096/tcp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/raid1/media:/media
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"

      traefik.http.routers.jellyfin.entrypoints: "web"
      traefik.http.routers.jellyfin.rule: "Host(`jellyfin.jpal.es`)"

      traefik.http.routers.jellyfin-insecure.entrypoints: "web"
      traefik.http.routers.jellyfin-insecure.rule: "Host(`jellyfin-insecure.jpal.es`)"

      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"

networks:
  traefik:
    external: true
